const districts = [
	{"districtCode":"1","districtNameShort":"Alabama","districtNameFull":"Alabama","missionsDirector":"Rev. David Strahan","address1":"5919 Carmichael Road","address2":"","city":"Montgomery","state":"AL","zip":"36117","zip4":"","phone":"(334) 279-7172","email":"dstrahan@adcag.org","fax":"","reqAssistanceInDistrict":"3","reqAssistanceOther":"5","reqAssistanceMA":"3"},
	{"districtCode":"2","districtNameShort":"Appalachian","districtNameFull":"Appalachian Ministry Network","missionsDirector":"Rev. David Dillon","address1":"PO Box 310","address2":"","city":"Ghent","state":"WV","zip":"25843-0310","zip4":"","phone":"(304) 787-3916","email":"ddilon_1@suddenlinkmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"3","districtNameShort":"Arizona","districtNameFull":"Arizona","missionsDirector":"Rev. Ron Rockwell","address1":"8340 West Northern Avenue","address2":"","city":"Glendale","state":"AZ","zip":"85305","zip4":"","phone":"(623) 334-9482","email":"teamrockwell@aol.com","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"5"},
	{"districtCode":"4","districtNameShort":"Arkansas","districtNameFull":"Arkansas","missionsDirector":"Rev. Cecil Culbreth","address1":"10924 Interstate 30","address2":"","city":"Little Rock","state":"AR","zip":"72209","zip4":"","phone":"(501) 455-5444","email":"cculbreth@araog.org","fax":"","reqAssistanceInDistrict":"3","reqAssistanceOther":"5","reqAssistanceMA":"3"},
	{"districtCode":"5","districtNameShort":"Pennsylvania-Delaware","districtNameFull":"Pennsylvania-Delaware","missionsDirector":"Rev. Jeff Marshal","address1":"4651 Westport Drive","address2":"","city":"Mechanicsburg","state":"PA","zip":"17055-4843","zip4":"","phone":"(717) 795-5921","email":"jeff@penndel.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"6","districtNameShort":"Georgia","districtNameFull":"Georgia","missionsDirector":"Rev. Joey Ellis","address1":"C/O Stone Edge Church 5659 Zebulon Rd","address2":"","city":"Macon","state":"GA","zip":"31210","zip4":"","phone":"(478) 474-9043","email":"joeye@stoneedgechurch.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"7","districtNameShort":"Illinois","districtNameFull":"Illinois","missionsDirector":"Rev. Phil Schneider","address1":"PO Box 620","address2":"","city":"Carlinville","state":"IL","zip":"62626-0620","zip4":"","phone":"(217) 854-4600","email":"phils@idcag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"8","districtNameShort":"Indiana","districtNameFull":"Indiana","missionsDirector":"Rev. Jon Susa","address1":"8750 Purdue Road","address2":"","city":"Indianapolis","state":"IN","zip":"46268-1120","zip4":"","phone":"(317) 897-7100","email":"jsusa@caringplace.tv","fax":"","reqAssistanceInDistrict":"4","reqAssistanceOther":"4","reqAssistanceMA":"0"},
	{"districtCode":"9","districtNameShort":"Kansas","districtNameFull":"Kansas Ministry Network","missionsDirector":"Rev. Andrew Parks","address1":"1016 N Pearl Street","address2":"","city":"Paola","state":"KS","zip":"66071","zip4":"","phone":"(316) 765-3389","email":"andy@cpchurch.tv","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"10","districtNameShort":"Kentucky","districtNameFull":"Kentucky","missionsDirector":"Rev. Martin Jacobson","address1":"144 Burnt Sienna Drive","address2":"","city":"Mount Washington","state":"KY","zip":"40047","zip4":"","phone":"(502) 504-1956","email":"martin.jacobson@agmd.org","fax":"","reqAssistanceInDistrict":"3","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"11","districtNameShort":"Louisiana","districtNameFull":"Louisiana District Council","missionsDirector":"Rev. Gary Sapp","address1":"P.O. Box 7388","address2":"","city":"Alexandria","state":"LA","zip":"71306","zip4":"","phone":"(318) 384-8057","email":"gary@laaog.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"12","districtNameShort":"Michigan","districtNameFull":"Michigan","missionsDirector":"Rev. Jeff Hlavin","address1":"10370 Citation Dr.","address2":"","city":"Brighton","state":"MI","zip":"48116","zip4":"","phone":"(810) 220-8700","email":"jhlavin@aogmi.org","fax":"","reqAssistanceInDistrict":"3","reqAssistanceOther":"3","reqAssistanceMA":"0"},
	{"districtCode":"13","districtNameShort":"Minnesota","districtNameFull":"Minnesota","missionsDirector":"Rev. Mark Boone","address1":"1315 Portland Avenue South","address2":"","city":"Minneapolis","state":"MN","zip":"55404-1454","zip4":"","phone":"(218) 820-7726","email":"mboone@mnaog.org","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"5","reqAssistanceMA":"2"},
	{"districtCode":"14","districtNameShort":"Mississippi","districtNameFull":"Mississippi","missionsDirector":"Rev. Gene Emswiler","address1":"15910 Highway 63","address2":"","city":"Moss Point","state":"MS","zip":"39562","zip4":"","phone":"(228) 588-2388","email":"gemswiler@threeriversag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"15","districtNameShort":"Montana","districtNameFull":"Montana Ministry Network","missionsDirector":"Rev. Dave Phillips","address1":"2147 Overland Ave, Ste 100","address2":"","city":"Billings","state":"MT","zip":"59102-6478","zip4":"","phone":"(406) 652-2417","email":"dave@mtaog.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"16","districtNameShort":"Nebraska","districtNameFull":"Nebraska","missionsDirector":"Rev. Mark Rose","address1":"200 North Victory Road","address2":"","city":"Norfolk","state":"NE","zip":"68701-6805","zip4":"","phone":"(402) 371-6288","email":"dmd@victoryroad.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"17","districtNameShort":"Northern New England","districtNameFull":"Northern New England","missionsDirector":"Rev. Dennis Marquardt","address1":"501 Riverside Street","address2":"","city":"Portland","state":"ME","zip":"04103","zip4":"","phone":"(207) 878-2777","email":"nneddm@maine.rr.com","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"18","districtNameShort":"New Jersey","districtNameFull":"New Jersey","missionsDirector":"Rev. Rich Leksell","address1":"PO Box 100","address2":"","city":"Burlington","state":"NJ","zip":"08016-0100","zip4":"","phone":"(609) 747-7878","email":"richl@njag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"3","reqAssistanceMA":"3"},
	{"districtCode":"19","districtNameShort":"New Mexico","districtNameFull":"New Mexico","missionsDirector":"Michael Dickenson","address1":"6640 Caminito Coors NW","address2":"","city":"Albuquerque","state":"NM","zip":"87120-3119","zip4":"","phone":"(505) 899-5399","email":"mdickenson@nmministry.net","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"5","reqAssistanceMA":"2"},
	{"districtCode":"20","districtNameShort":"New York","districtNameFull":"New York","missionsDirector":"Rev. Esther Terry","address1":"8130 Oswego Rd","address2":"","city":"Liverpool","state":"NY","zip":"13090-1575","zip4":"","phone":"(607) 797-3757","email":"eterry@calvaryslove.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"21","districtNameShort":"North Carolina","districtNameFull":"North Carolina AG Network","missionsDirector":"Rev. Rick Ross","address1":"PO Box 459","address2":"","city":"Selma","state":"NC","zip":"27576-0459","zip4":"","phone":"(919) 965-0225","email":"rross@ncag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"22","districtNameShort":"North Dakota","districtNameFull":"North Dakota","missionsDirector":"Rev. Winston Titus","address1":"1724 N Grandview Lane","address2":"","city":"Bismarck","state":"ND","zip":"58503","zip4":"","phone":"(701) 255-2526","email":"wtitus@nddcag.org","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"5","reqAssistanceMA":"2"},
	{"districtCode":"23","districtNameShort":"Northern Calif-Nevada","districtNameFull":"Northern California-Nevada","missionsDirector":"Bret Allen","address1":"PO Box 293510","address2":"","city":"Sacramento","state":"CA","zip":"95829","zip4":"","phone":"(916) 379-9600","email":"ballen@agncn.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"24","districtNameShort":"Northwest","districtNameFull":"Northwest Ministry Network","missionsDirector":"Rev. Dave Cole","address1":"35131 Southeast Douglas Street, Ste 200","address2":"","city":"Snoqualmie","state":"WA","zip":"98065-9233","zip4":"","phone":"(425) 888-4800","email":"davec@northwestministry.com","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"25","districtNameShort":"Ohio","districtNameFull":"Ohio Ministry Network","missionsDirector":"Rev. Dave Gross","address1":"8405 Pulsar Place","address2":"","city":"Columbus","state":"OH","zip":"43240-4043","zip4":"","phone":"(614) 396-0730","email":"dgross@ohioministry.net","fax":"","reqAssistanceInDistrict":"4","reqAssistanceOther":"4","reqAssistanceMA":"0"},
	{"districtCode":"26","districtNameShort":"Oklahoma","districtNameFull":"Oklahoma","missionsDirector":"Rev. Darren Pilcher","address1":"PO Box 13179","address2":"","city":"Oklahoma City","state":"OK","zip":"73113-1179","zip4":"","phone":"(405) 475-1132","email":"darren.pilcher@okag.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"27","districtNameShort":"Oregon","districtNameFull":"Oregon","missionsDirector":"Rev. Boyd Powers","address1":"5745 Inland Shores Way N","address2":"","city":"Keizer","state":"OR","zip":"97303","zip4":"","phone":"(503) 393-4411","email":"boyd.powers@oregonag.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"28","districtNameShort":"Potomac","districtNameFull":"Potomac","missionsDirector":"Rev. Mark Lehmann","address1":"16010 Annapolis Road","address2":"","city":"Bowie","state":"MD","zip":"20715","zip4":"","phone":"(301) 262-6266","email":"pastormark@cag.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"29","districtNameShort":"Rocky Mountain","districtNameFull":"Rocky Mountain Ministry Network","missionsDirector":"Rev. Bradley Williamson","address1":"6295 Lehman Drive, Ste. 202","address2":"","city":"Colorado Springs","state":"CO","zip":"80918-8434","zip4":"","phone":"(719) 522-0195","email":"missions@rmdc.org","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"5","reqAssistanceMA":"2"},
	{"districtCode":"30","districtNameShort":"South Carolina","districtNameFull":"South Carolina","missionsDirector":"Dr. Steven Allen","address1":"560 Ramblin Road","address2":"","city":"West Columbia","state":"SC","zip":"29170","zip4":"","phone":"(803) 936-0541","email":"sdarleneallen@yahoo.com","fax":"","reqAssistanceInDistrict":"3","reqAssistanceOther":"5","reqAssistanceMA":"3"},
	{"districtCode":"31","districtNameShort":"South Dakota","districtNameFull":"South Dakota","missionsDirector":"Rev. Kirk Strand","address1":"PO Box 91750","address2":"","city":"Sioux Falls","state":"SD","zip":"57109-1750","zip4":"","phone":"(605) 582-7622","email":"pastorbvag@gmail.com","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"32","districtNameShort":"Peninsular Florida","districtNameFull":"Peninsular Florida","missionsDirector":"Rev. Tom Manning","address1":"2699 West Commercial Blvd","address2":"","city":"Fort Lauderdale","state":"FL","zip":"33309","zip4":"","phone":"(954) 731-5433","email":"tommanning@clcftl.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"33","districtNameShort":"South Texas","districtNameFull":"South Texas","missionsDirector":"Rev. Roger Audorff","address1":"14237 E Sam Houston Pkwy N, Ste 200-314","address2":"","city":"Houston","state":"TX","zip":"77044","zip4":"","phone":"(713) 455-1221","email":"raudorff.stxag@gmail.com","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"34","districtNameShort":"Southern California","districtNameFull":"Southern California","missionsDirector":"Rev. John Johnson","address1":"17951 Cowan","address2":"","city":"Irvine","state":"CA","zip":"92614-6000","zip4":"","phone":"(949) 252-8400","email":"jjohnson@socalnetwork.org","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"35","districtNameShort":"Southern Idaho","districtNameFull":"Southern Idaho","missionsDirector":"Rev. Wayne Crownover","address1":"7225 E. Foxford Drive","address2":"","city":"Nampa","state":"ID","zip":"83687","zip4":"","phone":"(208) 375-1328","email":"wayne@rivercityboise.com","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"36","districtNameShort":"Southern Missouri","districtNameFull":"Southern Missouri","missionsDirector":"Rev. Stan Welch","address1":"528 West Battlefield Rd.","address2":"","city":"Springfield","state":"MO","zip":"65807-4122","zip4":"","phone":"(417) 881-1316","email":"stanwelch@somoag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"37","districtNameShort":"Tennessee","districtNameFull":"Tennessee AG Ministry Network","missionsDirector":"Rev. Terry Bailey","address1":"1402 Stop 30 Road","address2":"","city":"Hendersonville","state":"TN","zip":"37075","zip4":"","phone":"(615) 431-0871","email":"tbailey@tnaog.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"38","districtNameShort":"North Texas","districtNameFull":"North Texas","missionsDirector":"Rev. Kermit Bell","address1":"PO Box 838","address2":"","city":"Waxahachie","state":"TX","zip":"75168","zip4":"","phone":"(817) 284-4856","email":"kbell@northtexas.ag","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"39","districtNameShort":"Iowa","districtNameFull":"Iowa","missionsDirector":"Rev. Johnny Helton","address1":"4310 Old Lakeport Road","address2":"","city":"Sioux City","state":"IA","zip":"51106","zip4":"","phone":"(712) 276-4096","email":"jhelton@morningsideag.org","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"40","districtNameShort":"West Florida","districtNameFull":"West Florida","missionsDirector":"Rev. Tommy Moore","address1":"4792 Highway 90","address2":"","city":"Marianna","state":"FL","zip":"32446","zip4":"","phone":"(850) 482-2986","email":"supt@wfldag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"3","reqAssistanceMA":"0"},
	{"districtCode":"41","districtNameShort":"West Texas","districtNameFull":"West Texas","missionsDirector":"Rev. Glenn Beaver","address1":"PO Box 64778","address2":"","city":"Lubbock","state":"TX","zip":"79464-4778","zip4":"","phone":"(806) 792-5835","email":"grbeaver@sbcglobal.net","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"42","districtNameShort":"Wisconsin-N Michigan","districtNameFull":"Wisconsin-Northern Michigan","missionsDirector":"Rev. Gayland Hendrickson","address1":"PO Box 309","address2":"","city":"Waupaca","state":"WI","zip":"54981-0309","zip4":"","phone":"(715) 258-8118","email":"gayland@wnmdag.org","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"10","reqAssistanceMA":"0"},
	{"districtCode":"43","districtNameShort":"Wyoming","districtNameFull":"Wyoming Ministry Network","missionsDirector":"Rev. Craig Mellendorf","address1":"4301 Casper Mountain Road","address2":"","city":"Casper","state":"WY","zip":"82601","zip4":"","phone":"(307) 277-3668","email":"craigmellendorf@outlook.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"10","reqAssistanceMA":"0"},
	{"districtCode":"44","districtNameShort":"Southern New England","districtNameFull":"Southern New England","missionsDirector":"Rev. William Button","address1":"307 Sturbridge Rd.","address2":"","city":"Charlton","state":"MA","zip":"01507","zip4":"","phone":"(508) 248-3711","email":"bill@snemn.com","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"45","districtNameShort":"Northern Missouri","districtNameFull":"Northern Missouri","missionsDirector":"Rev. Tracy Cook","address1":"1010 N 7th Street","address2":"","city":"Columbia","state":"MO","zip":"65201","zip4":"","phone":"(573) 443-3626","email":"tcook@cfachurch.us","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"51","districtNameShort":"Alaska","districtNameFull":"Alaska Ministry Network","missionsDirector":"Rev. Gary Morton","address1":"1048 W Intl Airport Rd, Ste 101","address2":"","city":"Anchorage","state":"AK","zip":"99518-1005","zip4":"","phone":"(907) 276-1115","email":"gmorton7@gmail.com","fax":"","reqAssistanceInDistrict":"2","reqAssistanceOther":"2","reqAssistanceMA":"2"},
	{"districtCode":"53","districtNameShort":"Hawaii","districtNameFull":"Hawaii","missionsDirector":"Rev. Cir Domingo","address1":"122 Circle Mauka Street","address2":"","city":"Wahiawa","state":"HI","zip":"96786","zip4":"","phone":"(808) 622-4401","email":"cirdomingo@hawaiiantel.net","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"55","districtNameShort":"Puerto Rico","districtNameFull":"Puerto Rico","missionsDirector":"Rev. Marta Figueroa","address1":"PO Box 2787","address2":"","city":"Bayamon","state":"PR","zip":"00960-2787","zip4":"","phone":"(787) 798-5903","email":"martaymiguel1@hotmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"56","districtNameShort":"Florida Multicultural","districtNameFull":"Florida Multicultural","missionsDirector":"Rev. Diana Barrera","address1":"830 California Woods Circle","address2":"","city":"Orlando","state":"FL","zip":"32824-8809","zip4":"","phone":"(407) 850-9861","email":"dbarrera@fmdag.org","fax":"","reqAssistanceInDistrict":"3","reqAssistanceOther":"5","reqAssistanceMA":"3"},
	{"districtCode":"57","districtNameShort":"Korean","districtNameFull":"Korean","missionsDirector":"Rev. Myung Kim","address1":"7651 5th Street","address2":"","city":"Buena Park","state":"CA","zip":"90621","zip4":"","phone":"(201) 941-1050","email":"agkdc@hotmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"59","districtNameShort":"Brazilian","districtNameFull":"Brazilian","missionsDirector":"Rev. Joel F. Costa","address1":"3990 North Federal Highway","address2":"","city":"Lighthouse Point","state":"FL","zip":"33064-6043","zip4":"","phone":"(954) 782-0430","email":"adiicom@msn.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"60","districtNameShort":"German","districtNameFull":"German","missionsDirector":"Rev. Nathan Bloomfield","address1":"","address2":"","city":"","state":"","zip":"","zip4":"","phone":"","email":"nathan@blueroofchurch.com","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"61","districtNameShort":"Second Korean","districtNameFull":"Second Korean","missionsDirector":"Rev. Su B. Choe","address1":"PO Box 395","address2":"","city":"Spring Lake","state":"NC","zip":"28390","zip4":"","phone":"(910) 436-6060","email":"agskdc@gmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"62","districtNameShort":"National Slavic","districtNameFull":"National Slavic","missionsDirector":"Rev. Vitaly Zhelnovakov","address1":"PO Box 3023","address2":"","city":"Oregon City","state":"OR","zip":"97045","zip4":"","phone":"(855) 475-2842","email":"vzhelnovakov@slavicag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"65","districtNameShort":"West Texas and Plains","districtNameFull":"West Texas and Plains","missionsDirector":"Rev. Jose Portillo","address1":"11608 Coleen Way","address2":"","city":"El Paso","state":"TX","zip":"79936","zip4":"","phone":"(915) 422-7631","email":"asupt@wtapag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"66","districtNameShort":"Texas/Louisiana Hispanic","districtNameFull":"Texas/Louisiana Hispanic","missionsDirector":"Rev. Vincente Perez, Jr.","address1":"PO Box 1019","address2":"","city":"Poth","state":"TX","zip":"78147","zip4":"","phone":"(210) 441-8084","email":"vperez.dmd@txlahispanic.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"67","districtNameShort":"Southwest","districtNameFull":"Southwest","missionsDirector":"Rev. Burke Montoya","address1":"2601 East Thomas Road, Ste. 110","address2":"","city":"Phoenix","state":"AZ","zip":"85016-8228","zip4":"","phone":"(602) 956-5802","email":"pastorburke@cox.net","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"68","districtNameShort":"Central Pacific","districtNameFull":"Central Pacific","missionsDirector":"Rev. Jesse Galindo","address1":"6051 South Watt Avenue","address2":"","city":"Sacramento","state":"CA","zip":"95829","zip4":"","phone":"(916) 387-8800","email":"JGalindo@cpmnag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"69","districtNameShort":"Spanish Eastern","districtNameFull":"Spanish Eastern","missionsDirector":"Rev. Jacqueline Toro","address1":"197 Nostrand Avenue","address2":"","city":"Brooklyn","state":"NY","zip":"11205","zip4":"","phone":"(718) 875-8773","email":"misiones@sedag.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"70","districtNameShort":"Southern Pacific","districtNameFull":"Southern Pacific","missionsDirector":"Rev. Carlos Espana","address1":"614 South Fifth Avenue","address2":"","city":"La Puente","state":"CA","zip":"91746-3029","zip4":"","phone":"(626) 968-5088","email":"cespana@msn.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"2","reqAssistanceMA":"0"},
	{"districtCode":"71","districtNameShort":"Central District/Distrito Central","districtNameFull":"Central District/Distrito Central","missionsDirector":"Rev. Rigo Magana","address1":"P.O. Box 1594","address2":"","city":"Greeley","state":"CO","zip":"80632","zip4":"","phone":"(970) 352-8735","email":"Pastor.Rigo@hotmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"3","reqAssistanceMA":"3"},
	{"districtCode":"73","districtNameShort":"Midwest Latin American","districtNameFull":"Midwest Latin American","missionsDirector":"Rev. Edwin Marroquin","address1":"2001 Midwest Road Suite. 307","address2":"","city":"Oak Brook","state":"IL","zip":"60523","zip4":"","phone":"(314) 426-2210","email":"maranataad@sbcglobal.net","fax":"","reqAssistanceInDistrict":"5","reqAssistanceOther":"5","reqAssistanceMA":"5"},
	{"districtCode":"64","districtNameShort":"Texas Gulf Hispanic","districtNameFull":"Texas Gulf Hispanic","missionsDirector":"Rev. Rick Reyes","address1":"PO Box 2258","address2":"","city":"McAllen","state":"TX","zip":"78502","zip4":"","phone":"(956) 787-1737","email":"rreyes@txgulfhispanic.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"54","districtNameShort":"South Central Hispanic","districtNameFull":"South Central Hispanic","missionsDirector":"Rev. Armando Rodriguez","address1":"1709 S. L Street","address2":"","city":"Rogers","state":"AR","zip":"72756","zip4":"","phone":"(469) 531-5848","email":"armando.schd@gmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"5","reqAssistanceMA":"0"},
	{"districtCode":"74","districtNameShort":"Southern Latin","districtNameFull":"Southern Latin","missionsDirector":"Rev. David Zayas","address1":"524 Augusta Drive","address2":"","city":"Canton","state":"GA","zip":"30115","zip4":"","phone":"(404) 759-5446","email":"pastor.zayas@gmail.com","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"75","districtNameShort":"Northwest Hispanic","districtNameFull":"Northwest Hispanic","missionsDirector":"Rev. Enedeo Garza","address1":"2509 West Falls Avenue","address2":"","city":"Kennewick","state":"WA","zip":"99336","zip4":"","phone":"(509) 307-5820","email":"enedeo@nhdistrict.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"},
	{"districtCode":"52","districtNameShort":"Samoan","districtNameFull":"Samoan","missionsDirector":"Rev. Tuugasala L U Fuga","address1":"19804 Eighth Avenue South","address2":"","city":"Des Moines","state":"WA","zip":"98148","zip4":"","phone":"","email":"tfuga@sdcaog.org","fax":"","reqAssistanceInDistrict":"0","reqAssistanceOther":"0","reqAssistanceMA":"0"}
];

const sections = [
	{"section":"Andalusia","districtCode":"1"},
	{"section":"Anniston","districtCode":"1"},
	{"section":"Baldwin County","districtCode":"1"},
	{"section":"Birmingham","districtCode":"1"},
	{"section":"Cullman","districtCode":"1"},
	{"section":"Demopolis","districtCode":"1"},
	{"section":"Dothan","districtCode":"1"},
	{"section":"Enterprise","districtCode":"1"},
	{"section":"Mobile","districtCode":"1"},
	{"section":"Monroeville","districtCode":"1"},
	{"section":"Montgomery","districtCode":"1"},
	{"section":"Phenix City","districtCode":"1"},
	{"section":"Sylacauga","districtCode":"1"},
	{"section":"Tennessee Valley","districtCode":"1"},
	{"section":"Tuscaloosa","districtCode":"1"},
	{"section":"Central","districtCode":"51"},
	{"section":"Northern","districtCode":"51"},
	{"section":"Peninsula","districtCode":"51"},
	{"section":"Southeast","districtCode":"51"},
	{"section":"Western","districtCode":"51"},
	{"section":"01 Southwest","districtCode":"2"},
	{"section":"02 Two Virginias","districtCode":"2"},
	{"section":"03 Southeast","districtCode":"2"},
	{"section":"04 Blue Ridge-Metro","districtCode":"2"},
	{"section":"05 New River","districtCode":"2"},
	{"section":"06 Coalfields","districtCode":"2"},
	{"section":"07 Metro-River-Valley","districtCode":"2"},
	{"section":"08 Appalachian North","districtCode":"2"},
	{"section":"Canyon North","districtCode":"3"},
	{"section":"Central Valley","districtCode":"3"},
	{"section":"East","districtCode":"3"},
	{"section":"East Central","districtCode":"3"},
	{"section":"North Central","districtCode":"3"},
	{"section":"Northeast","districtCode":"3"},
	{"section":"Northwest","districtCode":"3"},
	{"section":"Northwest Valley","districtCode":"3"},
	{"section":"Phoenix Metro Indian","districtCode":"3"},
	{"section":"South","districtCode":"3"},
	{"section":"Southeast","districtCode":"3"},
	{"section":"Southeast Valley","districtCode":"3"},
	{"section":"Southwest","districtCode":"3"},
	{"section":"West Valley","districtCode":"3"},
	{"section":"01","districtCode":"4"},
	{"section":"02 East","districtCode":"4"},
	{"section":"02 West","districtCode":"4"},
	{"section":"03","districtCode":"4"},
	{"section":"04","districtCode":"4"},
	{"section":"05 North","districtCode":"4"},
	{"section":"05 South","districtCode":"4"},
	{"section":"06","districtCode":"4"},
	{"section":"07","districtCode":"4"},
	{"section":"08","districtCode":"4"},
	{"section":"09","districtCode":"4"},
	{"section":"10","districtCode":"4"},
	{"section":"11","districtCode":"4"},
	{"section":"12","districtCode":"4"},
	{"section":"13","districtCode":"4"},
	{"section":"14","districtCode":"4"},
	{"section":"15","districtCode":"4"},
	{"section":"Central","districtCode":"59"},
	{"section":"Mid - Atlantic","districtCode":"59"},
	{"section":"New England","districtCode":"59"},
	{"section":"Southeast","districtCode":"59"},
	{"section":"West","districtCode":"59"},
	{"section":"Region I","districtCode":"71"},
	{"section":"Region II","districtCode":"71"},
	{"section":"Region III","districtCode":"71"},
	{"section":"Region IV","districtCode":"71"},
	{"section":"Region V","districtCode":"71"},
	{"section":"Region VI","districtCode":"71"},
	{"section":"Bakersfield","districtCode":"68"},
	{"section":"East Bay","districtCode":"68"},
	{"section":"English","districtCode":"68"},
	{"section":"Fresno","districtCode":"68"},
	{"section":"Nevada","districtCode":"68"},
	{"section":"North Central California","districtCode":"68"},
	{"section":"North Central Washington","districtCode":"68"},
	{"section":"North Coastal California","districtCode":"68"},
	{"section":"Oregon","districtCode":"68"},
	{"section":"Sacramento","districtCode":"68"},
	{"section":"Salinas","districtCode":"68"},
	{"section":"San Francisco","districtCode":"68"},
	{"section":"San Joaquin Valley","districtCode":"68"},
	{"section":"San Jose","districtCode":"68"},
	{"section":"Seattle","districtCode":"68"},
	{"section":"South Eastern Washington","districtCode":"68"},
	{"section":"Southern Oregon","districtCode":"68"},
	{"section":"Stockton","districtCode":"68"},
	{"section":"Tri-County","districtCode":"68"},
	{"section":"Tulare","districtCode":"68"},
	{"section":"01","districtCode":"56"},
	{"section":"02","districtCode":"56"},
	{"section":"03","districtCode":"56"},
	{"section":"04","districtCode":"56"},
	{"section":"05","districtCode":"56"},
	{"section":"06","districtCode":"56"},
	{"section":"07","districtCode":"56"},
	{"section":"08","districtCode":"56"},
	{"section":"09","districtCode":"56"},
	{"section":"10","districtCode":"56"},
	{"section":"11","districtCode":"56"},
	{"section":"12","districtCode":"56"},
	{"section":"13","districtCode":"56"},
	{"section":"Albany","districtCode":"6"},
	{"section":"Athens","districtCode":"6"},
	{"section":"Augusta","districtCode":"6"},
	{"section":"Blakely","districtCode":"6"},
	{"section":"Columbus","districtCode":"6"},
	{"section":"Dublin","districtCode":"6"},
	{"section":"East Atlanta","districtCode":"6"},
	{"section":"Gainesville","districtCode":"6"},
	{"section":"Griffin","districtCode":"6"},
	{"section":"Macon","districtCode":"6"},
	{"section":"Moultrie","districtCode":"6"},
	{"section":"North Atlanta","districtCode":"6"},
	{"section":"Rome","districtCode":"6"},
	{"section":"Savannah","districtCode":"6"},
	{"section":"South Atlanta","districtCode":"6"},
	{"section":"Valdosta","districtCode":"6"},
	{"section":"Waycross","districtCode":"6"},
	{"section":"West Atlanta","districtCode":"6"},
	{"section":"Central","districtCode":"60"},
	{"section":"East","districtCode":"60"},
	{"section":"West","districtCode":"60"},
	{"section":"Central/Leeward Oahu","districtCode":"53"},
	{"section":"Hawaii","districtCode":"53"},
	{"section":"Kauai","districtCode":"53"},
	{"section":"Maui","districtCode":"53"},
	{"section":"Metro/Windward Oahu","districtCode":"53"},
	{"section":"Samoan","districtCode":"53"},
	{"section":"Central","districtCode":"7"},
	{"section":"Chicago","districtCode":"7"},
	{"section":"North","districtCode":"7"},
	{"section":"South","districtCode":"7"},
	{"section":"Indiana","districtCode":"8"},
	{"section":"01","districtCode":"39"},
	{"section":"02","districtCode":"39"},
	{"section":"03","districtCode":"39"},
	{"section":"04","districtCode":"39"},
	{"section":"05","districtCode":"39"},
	{"section":"06","districtCode":"39"},
	{"section":"07","districtCode":"39"},
	{"section":"Central","districtCode":"9"},
	{"section":"East","districtCode":"9"},
	{"section":"West","districtCode":"9"},
	{"section":"Bluegrass","districtCode":"10"},
	{"section":"Central","districtCode":"10"},
	{"section":"Cumberland","districtCode":"10"},
	{"section":"Jackson Purchase","districtCode":"10"},
	{"section":"Louisville","districtCode":"10"},
	{"section":"Mountain","districtCode":"10"},
	{"section":"Northcentral","districtCode":"10"},
	{"section":"Northeast","districtCode":"10"},
	{"section":"Northern","districtCode":"10"},
	{"section":"Pennyrile","districtCode":"10"},
	{"section":"Red River","districtCode":"10"},
	{"section":"Southcentral","districtCode":"10"},
	{"section":"Central-Eastern","districtCode":"57"},
	{"section":"North-Central","districtCode":"57"},
	{"section":"North-Eastern","districtCode":"57"},
	{"section":"North-Western","districtCode":"57"},
	{"section":"South-Central","districtCode":"57"},
	{"section":"South-Eastern","districtCode":"57"},
	{"section":"South-Western","districtCode":"57"},
	{"section":"Alexandria","districtCode":"11"},
	{"section":"Baton Rouge","districtCode":"11"},
	{"section":"Bossier City","districtCode":"11"},
	{"section":"Coushatta","districtCode":"11"},
	{"section":"Lafayette","districtCode":"11"},
	{"section":"Lake Charles","districtCode":"11"},
	{"section":"Leesville","districtCode":"11"},
	{"section":"New Orleans","districtCode":"11"},
	{"section":"New Orleans - Westbank","districtCode":"11"},
	{"section":"Northeast","districtCode":"11"},
	{"section":"Northlake","districtCode":"11"},
	{"section":"Raceland","districtCode":"11"},
	{"section":"Ruston","districtCode":"11"},
	{"section":"Shreveport","districtCode":"11"},
	{"section":"Winnfield","districtCode":"11"},
	{"section":"Wisner","districtCode":"11"},
	{"section":"Central","districtCode":"12"},
	{"section":"Metro","districtCode":"12"},
	{"section":"Metro East","districtCode":"12"},
	{"section":"Metro South","districtCode":"12"},
	{"section":"Metro West","districtCode":"12"},
	{"section":"North East","districtCode":"12"},
	{"section":"North West","districtCode":"12"},
	{"section":"Northern","districtCode":"12"},
	{"section":"South Central","districtCode":"12"},
	{"section":"South West","districtCode":"12"},
	{"section":"Thumb","districtCode":"12"},
	{"section":"West Central","districtCode":"12"},
	{"section":"Illinois","districtCode":"73"},
	{"section":"Indiana","districtCode":"73"},
	{"section":"Iowa","districtCode":"73"},
	{"section":"Kansas","districtCode":"73"},
	{"section":"Michigan","districtCode":"73"},
	{"section":"Minnesota","districtCode":"73"},
	{"section":"Missouri","districtCode":"73"},
	{"section":"Nebraska","districtCode":"73"},
	{"section":"North Dakota","districtCode":"73"},
	{"section":"South Dakota","districtCode":"73"},
	{"section":"Wisconsin","districtCode":"73"},
	{"section":"Central","districtCode":"13"},
	{"section":"East Central","districtCode":"13"},
	{"section":"East Twin Cities","districtCode":"13"},
	{"section":"Eastern","districtCode":"13"},
	{"section":"Hmong","districtCode":"13"},
	{"section":"Inner Urban","districtCode":"13"},
	{"section":"Middle West","districtCode":"13"},
	{"section":"North Twin Cities","districtCode":"13"},
	{"section":"Northeast","districtCode":"13"},
	{"section":"Northwest","districtCode":"13"},
	{"section":"South Central","districtCode":"13"},
	{"section":"South Twin Cities","districtCode":"13"},
	{"section":"Southeast","districtCode":"13"},
	{"section":"Southwest","districtCode":"13"},
	{"section":"West Central","districtCode":"13"},
	{"section":"West Twin Cities","districtCode":"13"},
	{"section":"Biloxi","districtCode":"14"},
	{"section":"Columbus","districtCode":"14"},
	{"section":"Greenville","districtCode":"14"},
	{"section":"Hattiesburg","districtCode":"14"},
	{"section":"Jackson","districtCode":"14"},
	{"section":"McComb","districtCode":"14"},
	{"section":"Meridian","districtCode":"14"},
	{"section":"Pascagoula","districtCode":"14"},
	{"section":"Southaven","districtCode":"14"},
	{"section":"Tupelo","districtCode":"14"},
	{"section":"Water Valley","districtCode":"14"},
	{"section":"Waynesboro","districtCode":"14"},
	{"section":"Capitol","districtCode":"15"},
	{"section":"Custer","districtCode":"15"},
	{"section":"Five Valleys","districtCode":"15"},
	{"section":"Flathead","districtCode":"15"},
	{"section":"Fort Peck","districtCode":"15"},
	{"section":"Milk River","districtCode":"15"},
	{"section":"Teton","districtCode":"15"},
	{"section":"Yellowstone","districtCode":"15"},
	{"section":"Slavic","districtCode":"62"},
	{"section":"Capital","districtCode":"16"},
	{"section":"Eppley","districtCode":"16"},
	{"section":"Niobrara","districtCode":"16"},
	{"section":"Northwest","districtCode":"16"},
	{"section":"Offutt","districtCode":"16"},
	{"section":"Republican Valley","districtCode":"16"},
	{"section":"Rock Creek","districtCode":"16"},
	{"section":"Sandhills","districtCode":"16"},
	{"section":"Siouxland","districtCode":"16"},
	{"section":"Southern Panhandle","districtCode":"16"},
	{"section":"Tri-City","districtCode":"16"},
	{"section":"East Central North","districtCode":"18"},
	{"section":"East Central South","districtCode":"18"},
	{"section":"Northeast","districtCode":"18"},
	{"section":"Northern","districtCode":"18"},
	{"section":"Northwest","districtCode":"18"},
	{"section":"Southern","districtCode":"18"},
	{"section":"West Central North","districtCode":"18"},
	{"section":"West Central South","districtCode":"18"},
	{"section":"East Central","districtCode":"19"},
	{"section":"Native American","districtCode":"19"},
	{"section":"Northeast","districtCode":"19"},
	{"section":"Northwest","districtCode":"19"},
	{"section":"Southeast","districtCode":"19"},
	{"section":"Southwest","districtCode":"19"},
	{"section":"West Central","districtCode":"19"},
	{"section":"Capital","districtCode":"20"},
	{"section":"Central","districtCode":"20"},
	{"section":"Hudson Valley","districtCode":"20"},
	{"section":"Lakeshore","districtCode":"20"},
	{"section":"Long Island","districtCode":"20"},
	{"section":"North Central","districtCode":"20"},
	{"section":"Northeast","districtCode":"20"},
	{"section":"Nyc/Bronx/Manhat","districtCode":"20"},
	{"section":"Nyc/Brooklyn/Staten Island","districtCode":"20"},
	{"section":"Nyc/Queens","districtCode":"20"},
	{"section":"South Central","districtCode":"20"},
	{"section":"Southern Tier","districtCode":"20"},
	{"section":"Western","districtCode":"20"},
	{"section":"Central","districtCode":"21"},
	{"section":"Eastern","districtCode":"21"},
	{"section":"Western","districtCode":"21"},
	{"section":"North Central","districtCode":"22"},
	{"section":"Northeast","districtCode":"22"},
	{"section":"Northwest","districtCode":"22"},
	{"section":"South Central","districtCode":"22"},
	{"section":"Southeast","districtCode":"22"},
	{"section":"Southwest","districtCode":"22"},
	{"section":"Abilene","districtCode":"38"},
	{"section":"Brazos Valley","districtCode":"38"},
	{"section":"Corsicana","districtCode":"38"},
	{"section":"Cross Timbers","districtCode":"38"},
	{"section":"Denton","districtCode":"38"},
	{"section":"Grand Prairie","districtCode":"38"},
	{"section":"Greenville","districtCode":"38"},
	{"section":"Longview","districtCode":"38"},
	{"section":"Lufkin","districtCode":"38"},
	{"section":"Metro East","districtCode":"38"},
	{"section":"Mid-Cities","districtCode":"38"},
	{"section":"Nacogdoches","districtCode":"38"},
	{"section":"North Austin","districtCode":"38"},
	{"section":"North Dallas","districtCode":"38"},
	{"section":"North East Fort Worth","districtCode":"38"},
	{"section":"North West Forth Worth","districtCode":"38"},
	{"section":"Plano","districtCode":"38"},
	{"section":"Red River","districtCode":"38"},
	{"section":"Rockwall","districtCode":"38"},
	{"section":"San Angelo","districtCode":"38"},
	{"section":"South Austin","districtCode":"38"},
	{"section":"South Dallas","districtCode":"38"},
	{"section":"South Fort Worth","districtCode":"38"},
	{"section":"Texarkana","districtCode":"38"},
	{"section":"Trinity Valley","districtCode":"38"},
	{"section":"Tyler","districtCode":"38"},
	{"section":"Waco","districtCode":"38"},
	{"section":"Waxahachie","districtCode":"38"},
	{"section":"Wichita Falls","districtCode":"38"},
	{"section":"Butte","districtCode":"23"},
	{"section":"Central San Joaquin","districtCode":"23"},
	{"section":"Coast Counties","districtCode":"23"},
	{"section":"Contra Costa","districtCode":"23"},
	{"section":"East Bay","districtCode":"23"},
	{"section":"Foothill","districtCode":"23"},
	{"section":"Gold Country","districtCode":"23"},
	{"section":"Lake Berryessa","districtCode":"23"},
	{"section":"Lake-Mendocino","districtCode":"23"},
	{"section":"Lassen-Plumas","districtCode":"23"},
	{"section":"Mt Shasta","districtCode":"23"},
	{"section":"North Bay","districtCode":"23"},
	{"section":"North Capital","districtCode":"23"},
	{"section":"North San Joaquin","districtCode":"23"},
	{"section":"Northern Nevada","districtCode":"23"},
	{"section":"Peninsula","districtCode":"23"},
	{"section":"Redwood","districtCode":"23"},
	{"section":"Sacramento Valley","districtCode":"23"},
	{"section":"Sierra Nevada","districtCode":"23"},
	{"section":"South Bay","districtCode":"23"},
	{"section":"South Capital","districtCode":"23"},
	{"section":"South San Joaquin","districtCode":"23"},
	{"section":"Southern Nevada","districtCode":"23"},
	{"section":"Valley Ridge","districtCode":"23"},
	{"section":"01","districtCode":"45"},
	{"section":"02","districtCode":"45"},
	{"section":"03","districtCode":"45"},
	{"section":"04","districtCode":"45"},
	{"section":"05","districtCode":"45"},
	{"section":"06","districtCode":"45"},
	{"section":"Aroostook","districtCode":"17"},
	{"section":"Central","districtCode":"17"},
	{"section":"North Central","districtCode":"17"},
	{"section":"Northern","districtCode":"17"},
	{"section":"Northwest","districtCode":"17"},
	{"section":"Southeast","districtCode":"17"},
	{"section":"Southwest","districtCode":"17"},
	{"section":"White Mountain","districtCode":"17"},
	{"section":"Capital","districtCode":"24"},
	{"section":"Columbia Basin","districtCode":"24"},
	{"section":"Greater Everett","districtCode":"24"},
	{"section":"Greater Tacoma","districtCode":"24"},
	{"section":"Lower Columbia","districtCode":"24"},
	{"section":"Metro East","districtCode":"24"},
	{"section":"Metro North","districtCode":"24"},
	{"section":"Metro Northeast","districtCode":"24"},
	{"section":"Metro South","districtCode":"24"},
	{"section":"Metro West","districtCode":"24"},
	{"section":"Mount Baker","districtCode":"24"},
	{"section":"Mount Rainier","districtCode":"24"},
	{"section":"North Idaho","districtCode":"24"},
	{"section":"Northern Idaho","districtCode":"24"},
	{"section":"Okanogan","districtCode":"24"},
	{"section":"Olympic Peninsula","districtCode":"24"},
	{"section":"Skagit","districtCode":"24"},
	{"section":"Snake River","districtCode":"24"},
	{"section":"Spokane","districtCode":"24"},
	{"section":"Tacoma East","districtCode":"24"},
	{"section":"Tacoma West","districtCode":"24"},
	{"section":"Tri-Cities","districtCode":"24"},
	{"section":"Upper Columbia","districtCode":"24"},
	{"section":"Wenatchee Valley","districtCode":"24"},
	{"section":"West Sound","districtCode":"24"},
	{"section":"Yakima","districtCode":"24"},
	{"section":"Yakima/Tricities","districtCode":"24"},
	{"section":"East Central Oregon","districtCode":"75"},
	{"section":"East Or","districtCode":"75"},
	{"section":"North Central Wa","districtCode":"75"},
	{"section":"North Central Washington","districtCode":"75"},
	{"section":"North East Washington","districtCode":"75"},
	{"section":"North Or","districtCode":"75"},
	{"section":"North West Oregon","districtCode":"75"},
	{"section":"North West Washington","districtCode":"75"},
	{"section":"Seattle","districtCode":"75"},
	{"section":"South Central Washington","districtCode":"75"},
	{"section":"South East Washington","districtCode":"75"},
	{"section":"South Eastern Wa","districtCode":"75"},
	{"section":"South Or","districtCode":"75"},
	{"section":"South West Oregon","districtCode":"75"},
	{"section":"South West Washington","districtCode":"75"},
	{"section":"East Central","districtCode":"25"},
	{"section":"Greater Akron","districtCode":"25"},
	{"section":"Greater Cincinnati","districtCode":"25"},
	{"section":"Greater Cleveland","districtCode":"25"},
	{"section":"Greater Columbus East","districtCode":"25"},
	{"section":"Greater Columbus West","districtCode":"25"},
	{"section":"Greater Dayton","districtCode":"25"},
	{"section":"North Central","districtCode":"25"},
	{"section":"Northeast","districtCode":"25"},
	{"section":"Northwest","districtCode":"25"},
	{"section":"South Central","districtCode":"25"},
	{"section":"Southeast","districtCode":"25"},
	{"section":"West Central","districtCode":"25"},
	{"section":"Youngstown-Warren","districtCode":"25"},
	{"section":"01","districtCode":"26"},
	{"section":"02","districtCode":"26"},
	{"section":"03","districtCode":"26"},
	{"section":"04","districtCode":"26"},
	{"section":"05 East","districtCode":"26"},
	{"section":"05 West","districtCode":"26"},
	{"section":"06","districtCode":"26"},
	{"section":"07","districtCode":"26"},
	{"section":"08","districtCode":"26"},
	{"section":"09 North","districtCode":"26"},
	{"section":"09 South","districtCode":"26"},
	{"section":"10","districtCode":"26"},
	{"section":"11","districtCode":"26"},
	{"section":"12","districtCode":"26"},
	{"section":"Blue Mountain","districtCode":"27"},
	{"section":"Capitol","districtCode":"27"},
	{"section":"Central","districtCode":"27"},
	{"section":"East Metro","districtCode":"27"},
	{"section":"Grand Ronde","districtCode":"27"},
	{"section":"Klamath","districtCode":"27"},
	{"section":"Lower Columbia","districtCode":"27"},
	{"section":"North Coast","districtCode":"27"},
	{"section":"Rogue Valley","districtCode":"27"},
	{"section":"South Coast","districtCode":"27"},
	{"section":"South Willamette","districtCode":"27"},
	{"section":"Umpqua","districtCode":"27"},
	{"section":"West Metro","districtCode":"27"},
	{"section":"Avon Park","districtCode":"32"},
	{"section":"British Virgin Islands","districtCode":"32"},
	{"section":"Clearwater","districtCode":"32"},
	{"section":"Dade City","districtCode":"32"},
	{"section":"Daytona","districtCode":"32"},
	{"section":"Ft Lauderdale","districtCode":"32"},
	{"section":"Ft Myers","districtCode":"32"},
	{"section":"Gainesville","districtCode":"32"},
	{"section":"Hillsborough Cty","districtCode":"32"},
	{"section":"Lakeland","districtCode":"32"},
	{"section":"Miami","districtCode":"32"},
	{"section":"North Jacksonville","districtCode":"32"},
	{"section":"Ocala","districtCode":"32"},
	{"section":"Orlando","districtCode":"32"},
	{"section":"Sarasota","districtCode":"32"},
	{"section":"South Jacksonville","districtCode":"32"},
	{"section":"Tampa","districtCode":"32"},
	{"section":"US Virgin Islands","districtCode":"32"},
	{"section":"West Palm Beach","districtCode":"32"},
	{"section":"Delmarva","districtCode":"5"},
	{"section":"East Central","districtCode":"5"},
	{"section":"North Central","districtCode":"5"},
	{"section":"North Central West","districtCode":"5"},
	{"section":"North East","districtCode":"5"},
	{"section":"North West","districtCode":"5"},
	{"section":"South Central","districtCode":"5"},
	{"section":"South Central East","districtCode":"5"},
	{"section":"South Central West","districtCode":"5"},
	{"section":"Southeast","districtCode":"5"},
	{"section":"Southwest Metro","districtCode":"5"},
	{"section":"Southwest Suburb","districtCode":"5"},
	{"section":"Baltimore 1","districtCode":"28"},
	{"section":"Baltimore 2","districtCode":"28"},
	{"section":"Baltimore 3","districtCode":"28"},
	{"section":"Central 1","districtCode":"28"},
	{"section":"Central 2","districtCode":"28"},
	{"section":"Central 3","districtCode":"28"},
	{"section":"Central 4","districtCode":"28"},
	{"section":"Central 5","districtCode":"28"},
	{"section":"Central 6","districtCode":"28"},
	{"section":"Coastal 1","districtCode":"28"},
	{"section":"Coastal 2","districtCode":"28"},
	{"section":"Coastal 3","districtCode":"28"},
	{"section":"Coastal 4","districtCode":"28"},
	{"section":"Coastal 5","districtCode":"28"},
	{"section":"Coastal 6","districtCode":"28"},
	{"section":"Southern 1","districtCode":"28"},
	{"section":"Southern 2","districtCode":"28"},
	{"section":"Southern 3","districtCode":"28"},
	{"section":"Southern 4","districtCode":"28"},
	{"section":"Southern 5","districtCode":"28"},
	{"section":"Washington 1","districtCode":"28"},
	{"section":"Washington 2","districtCode":"28"},
	{"section":"Washington 3","districtCode":"28"},
	{"section":"Washington 4","districtCode":"28"},
	{"section":"Washington 5","districtCode":"28"},
	{"section":"Washington 6","districtCode":"28"},
	{"section":"Western 1","districtCode":"28"},
	{"section":"Western 2","districtCode":"28"},
	{"section":"Western 3","districtCode":"28"},
	{"section":"Western 4","districtCode":"28"},
	{"section":"Western 5","districtCode":"28"},
	{"section":"Western 6","districtCode":"28"},
	{"section":"Western 7","districtCode":"28"},
	{"section":"Central","districtCode":"55"},
	{"section":"Central East","districtCode":"55"},
	{"section":"East","districtCode":"55"},
	{"section":"North","districtCode":"55"},
	{"section":"North Central","districtCode":"55"},
	{"section":"North East","districtCode":"55"},
	{"section":"North West","districtCode":"55"},
	{"section":"South","districtCode":"55"},
	{"section":"South East","districtCode":"55"},
	{"section":"South West","districtCode":"55"},
	{"section":"West","districtCode":"55"},
	{"section":"West Central","districtCode":"55"},
	{"section":"Denver Metro North","districtCode":"29"},
	{"section":"Denver Metro South","districtCode":"29"},
	{"section":"Mountain","districtCode":"29"},
	{"section":"North East","districtCode":"29"},
	{"section":"North West","districtCode":"29"},
	{"section":"Northern","districtCode":"29"},
	{"section":"Northern Utah","districtCode":"29"},
	{"section":"Pikes Peak","districtCode":"29"},
	{"section":"San Juan","districtCode":"29"},
	{"section":"South East","districtCode":"29"},
	{"section":"Southern","districtCode":"29"},
	{"section":"Southern Utah","districtCode":"29"},
	{"section":"West Central","districtCode":"29"},
	{"section":"Alaska","districtCode":"52"},
	{"section":"Hawaii","districtCode":"52"},
	{"section":"Northern California","districtCode":"52"},
	{"section":"Northwest","districtCode":"52"},
	{"section":"Southern California","districtCode":"52"},
	{"section":"Section 2","districtCode":"61"},
	{"section":"Aiken-Orangeburg","districtCode":"30"},
	{"section":"Anderson-Seneca","districtCode":"30"},
	{"section":"Charleston-Summerville","districtCode":"30"},
	{"section":"Columbia","districtCode":"30"},
	{"section":"Florence-Sumter","districtCode":"30"},
	{"section":"Georgetown-Grand Strand","districtCode":"30"},
	{"section":"Greenville-Greer","districtCode":"30"},
	{"section":"Greenwood-Laurens","districtCode":"30"},
	{"section":"Hampton-Port Royal","districtCode":"30"},
	{"section":"Rock Hill-Lancaster","districtCode":"30"},
	{"section":"Spartanburg-Union","districtCode":"30"},
	{"section":"Arkansas - Northwest","districtCode":"54"},
	{"section":"Arkansas - South-Central","districtCode":"54"},
	{"section":"Arkansas - Southwest","districtCode":"54"},
	{"section":"Dallas - Northeast","districtCode":"54"},
	{"section":"Dallas - Northwest","districtCode":"54"},
	{"section":"Dallas - Southeast","districtCode":"54"},
	{"section":"Fort Worth","districtCode":"54"},
	{"section":"Oklahoma","districtCode":"54"},
	{"section":"Tyler","districtCode":"54"},
	{"section":"Waco","districtCode":"54"},
	{"section":"Wichita Falls","districtCode":"54"},
	{"section":"Black Hills","districtCode":"31"},
	{"section":"Central","districtCode":"31"},
	{"section":"East Central","districtCode":"31"},
	{"section":"Northeast","districtCode":"31"},
	{"section":"Southeast","districtCode":"31"},
	{"section":"Beaumont","districtCode":"33"},
	{"section":"Corpus Christi","districtCode":"33"},
	{"section":"Gulf Coast","districtCode":"33"},
	{"section":"Houston","districtCode":"33"},
	{"section":"Neches Valley","districtCode":"33"},
	{"section":"North Houston","districtCode":"33"},
	{"section":"Rio Grande Valley","districtCode":"33"},
	{"section":"San Antonio","districtCode":"33"},
	{"section":"San Jacinto","districtCode":"33"},
	{"section":"Victoria","districtCode":"33"},
	{"section":"Region 1","districtCode":"34"},
	{"section":"Region 2","districtCode":"34"},
	{"section":"Region 3","districtCode":"34"},
	{"section":"Region 4","districtCode":"34"},
	{"section":"Region 5","districtCode":"34"},
	{"section":"Region 6","districtCode":"34"},
	{"section":"Region 7","districtCode":"34"},
	{"section":"Region 8","districtCode":"34"},
	{"section":"Region 9","districtCode":"34"},
	{"section":"Region 10","districtCode":"34"},
	{"section":"Region 11","districtCode":"34"},
	{"section":"Region 12","districtCode":"34"},
	{"section":"01","districtCode":"35"},
	{"section":"02","districtCode":"35"},
	{"section":"Alabama/Mississippi","districtCode":"74"},
	{"section":"Georgia East","districtCode":"74"},
	{"section":"Georgia North","districtCode":"74"},
	{"section":"Georgia South","districtCode":"74"},
	{"section":"Georgia West","districtCode":"74"},
	{"section":"North/South Carolina","districtCode":"74"},
	{"section":"Cape Girardeau","districtCode":"36"},
	{"section":"Clinton","districtCode":"36"},
	{"section":"Joplin","districtCode":"36"},
	{"section":"Kansas City","districtCode":"36"},
	{"section":"Kennett","districtCode":"36"},
	{"section":"Park Hills","districtCode":"36"},
	{"section":"Sedalia","districtCode":"36"},
	{"section":"Springfield-North","districtCode":"36"},
	{"section":"Springfield-South","districtCode":"36"},
	{"section":"St Louis","districtCode":"36"},
	{"section":"Sullivan","districtCode":"36"},
	{"section":"Van Buren","districtCode":"36"},
	{"section":"West Plains","districtCode":"36"},
	{"section":"Boston","districtCode":"44"},
	{"section":"Central Massachusetts","districtCode":"44"},
	{"section":"Eastern Connecticut","districtCode":"44"},
	{"section":"Northeastern Massachusetts","districtCode":"44"},
	{"section":"Northwestern Connecticut","districtCode":"44"},
	{"section":"Rhode Island","districtCode":"44"},
	{"section":"Southeastern Massachusetts","districtCode":"44"},
	{"section":"Southwestern Connecticut","districtCode":"44"},
	{"section":"Western Massachusetts","districtCode":"44"},
	{"section":"Region I","districtCode":"70"},
	{"section":"Region II","districtCode":"70"},
	{"section":"Region III","districtCode":"70"},
	{"section":"Region IV","districtCode":"70"},
	{"section":"Region V","districtCode":"70"},
	{"section":"Region VI","districtCode":"70"},
	{"section":"Region VII","districtCode":"70"},
	{"section":"Arizona","districtCode":"67"},
	{"section":"English Region","districtCode":"67"},
	{"section":"Phoenix","districtCode":"67"},
	{"section":"Tucson","districtCode":"67"},
	{"section":"Yuma","districtCode":"67"},
	{"section":"Bronx","districtCode":"69"},
	{"section":"Brooklyn","districtCode":"69"},
	{"section":"Columbia","districtCode":"69"},
	{"section":"Connecticut","districtCode":"69"},
	{"section":"Kentucky","districtCode":"69"},
	{"section":"Long Island","districtCode":"69"},
	{"section":"Manhattan","districtCode":"69"},
	{"section":"New England","districtCode":"69"},
	{"section":"New England North","districtCode":"69"},
	{"section":"New England South","districtCode":"69"},
	{"section":"New Jersey North","districtCode":"69"},
	{"section":"New Jersey South & Delaware","districtCode":"69"},
	{"section":"Northwest","districtCode":"69"},
	{"section":"Ohio","districtCode":"69"},
	{"section":"Pennsylvania","districtCode":"69"},
	{"section":"Queens","districtCode":"69"},
	{"section":"Tennessee","districtCode":"69"},
	{"section":"Upstate","districtCode":"69"},
	{"section":"Chattanooga","districtCode":"37"},
	{"section":"Columbia","districtCode":"37"},
	{"section":"Cookeville","districtCode":"37"},
	{"section":"Covington","districtCode":"37"},
	{"section":"Dyersburg","districtCode":"37"},
	{"section":"Hispanic","districtCode":"37"},
	{"section":"Jackson","districtCode":"37"},
	{"section":"Knoxville","districtCode":"37"},
	{"section":"Memphis","districtCode":"37"},
	{"section":"Milan","districtCode":"37"},
	{"section":"Nashville North","districtCode":"37"},
	{"section":"Nashville South","districtCode":"37"},
	{"section":"Ripley","districtCode":"37"},
	{"section":"Tri-Cities","districtCode":"37"},
	{"section":"Brownsville","districtCode":"64"},
	{"section":"Corpus Christi Network","districtCode":"64"},
	{"section":"Harlingen Network","districtCode":"64"},
	{"section":"Laredo Network","districtCode":"64"},
	{"section":"McAllen Network","districtCode":"64"},
	{"section":"Mission","districtCode":"64"},
	{"section":"Uvalde Network","districtCode":"64"},
	{"section":"Austin","districtCode":"66"},
	{"section":"Central Houston","districtCode":"66"},
	{"section":"East San Antonio","districtCode":"66"},
	{"section":"Galveston","districtCode":"66"},
	{"section":"Louisiana","districtCode":"66"},
	{"section":"North Houston","districtCode":"66"},
	{"section":"Rosenburg","districtCode":"66"},
	{"section":"South East Houston","districtCode":"66"},
	{"section":"West San Antonio","districtCode":"66"},
	{"section":"01","districtCode":"40"},
	{"section":"02","districtCode":"40"},
	{"section":"03","districtCode":"40"},
	{"section":"04A","districtCode":"40"},
	{"section":"04B","districtCode":"40"},
	{"section":"05","districtCode":"40"},
	{"section":"06","districtCode":"40"},
	{"section":"07","districtCode":"40"},
	{"section":"08","districtCode":"40"},
	{"section":"09","districtCode":"40"},
	{"section":"10","districtCode":"40"},
	{"section":"11","districtCode":"40"},
	{"section":"12","districtCode":"40"},
	{"section":"East Plains","districtCode":"41"},
	{"section":"El Paso","districtCode":"41"},
	{"section":"North Plains","districtCode":"41"},
	{"section":"Pecos","districtCode":"41"},
	{"section":"South Plains","districtCode":"41"},
	{"section":"West Plains","districtCode":"41"},
	{"section":"Central","districtCode":"65"},
	{"section":"East","districtCode":"65"},
	{"section":"North","districtCode":"65"},
	{"section":"South","districtCode":"65"},
	{"section":"West","districtCode":"65"},
	{"section":"Section 1","districtCode":"42"},
	{"section":"Section 2","districtCode":"42"},
	{"section":"Section 3","districtCode":"42"},
	{"section":"Section 4","districtCode":"42"},
	{"section":"Section 5","districtCode":"42"},
	{"section":"Section 6","districtCode":"42"},
	{"section":"Section 7","districtCode":"42"},
	{"section":"Section 8","districtCode":"42"},
	{"section":"Section 9","districtCode":"42"},
	{"section":"Section 10","districtCode":"42"},
	{"section":"Section 11","districtCode":"42"},
	{"section":"Central","districtCode":"43"},
	{"section":"Northeast","districtCode":"43"},
	{"section":"Northwest","districtCode":"43"},
	{"section":"Southeast","districtCode":"43"},
	{"section":"Southwest","districtCode":"43"},
	{"section":"West Central","districtCode":"43"}
	]

export { districts, sections }