name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: build frontend
        working-directory: ./frontend
        - run:
          npm run build
      name: build backend
        working-directory: ./backend
        - run:
          npm run build
      name: deploying
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "app-imp" #Must be unique in Heroku
            heroku_email: "jozue06@gmail.com"